@echo off
echo ===============================================
echo   PROJECT CLEANUP SCRIPT
echo ===============================================
echo.

echo Cleaning build files...
if exist "build\*.exe" del /Q "build\*.exe"
if exist "build\*.o" del /Q "build\*.o"
if exist "obj\*" del /Q /S "obj\*"

echo Cleaning temporary files...
if exist "*.tmp" del /Q "*.tmp"
if exist "*.log" del /Q "*.log"
if exist "*~" del /Q "*~"

echo Cleaning generated data files (keeping structure)...
REM Keep the CSV files as they are generated by the application

echo.
echo ✓ Project cleaned successfully!
echo.
echo To rebuild the project, run: build.bat
echo.
pause
